# Generated by Django 3.0.5 on 2020-10-25 02:01

import amenities.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('amenityType', djongo.models.fields.EmbeddedField(model_container=amenities.models.AmenityType)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
    ]
