# Generated by Django 3.0.5 on 2020-10-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
