# Generated by Django 3.0.5 on 2020-10-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_auto_20201024_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Establishments',
            new_name='EstablishmentTypes',
        ),
        migrations.AlterModelTable(
            name='establishmenttypes',
            table='establishment_types',
        ),
    ]
